/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import modell.Palya;
import java.util.Random;

/**
 *
 * @author pille
 */
public class Gui extends javax.swing.JFrame {
    private Palya palya = new Palya();
    private final int HOSSZ = palya.getHOSSZ();
    private final String HARCOS = palya.getHARCOS(), VARAZSLO = palya.getVARAZSLO(), URES = palya.getURES(), HARC = palya.getHARC();
    private String[] mezok = new String[HOSSZ];
    private int harcosHP = 10, varazsloHP = 10;
    private Random r = new Random();
    
    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
        
        alaphelyzet();
        palyatMutat();
        adatotMutat();
    }

    public void alaphelyzet() {
        palya = new Palya();
        mezok = palya.getMezok();
        harcosHP = 10;
        varazsloHP = 10;
        btnLepes.setEnabled(true);
        lblGyoztes.setText("A győztes: ");
    }
    
    public void palyatMutat() {
        String egeszPalya = "";
        for(int i = 0; i < mezok.length; i++) egeszPalya += mezok[i];
        lblMezok.setText(egeszPalya);
    }
    
    public void adatotMutat() {
        lblHarcosHP.setText("Harcos HP: " + harcosHP);
        lblVarazsloHP.setText("Varázsló HP: " + varazsloHP);
    }
    
    private void harc() {
        harcosHP -= r.nextInt(1, 4);
        varazsloHP -= r.nextInt(1, 4);
        jatekVege();
    }
    
    private void jatekVege() {
        String vege = "A győztes: ";
        boolean lepes = false;
        if(varazsloHP <= 0 && harcosHP <= 0) vege += "Döntetlen";
        else if(harcosHP <= 0) vege += "Varázsló";
        else if(varazsloHP <= 0) vege += "Harcos";
        else lepes = true;
        lblGyoztes.setText(vege);
        btnLepes.setEnabled(lepes);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLepes = new javax.swing.JButton();
        btnUjra = new javax.swing.JButton();
        lblHarcosHP = new javax.swing.JLabel();
        lblVarazsloHP = new javax.swing.JLabel();
        lblGyoztes = new javax.swing.JLabel();
        lblMezok = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Harcos és Varázsló");
        setResizable(false);

        btnLepes.setText("Lépés");
        btnLepes.setPreferredSize(new java.awt.Dimension(80, 30));
        btnLepes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLepesActionPerformed(evt);
            }
        });

        btnUjra.setText("Újra");
        btnUjra.setPreferredSize(new java.awt.Dimension(80, 30));
        btnUjra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUjraActionPerformed(evt);
            }
        });

        lblHarcosHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHarcosHP.setText("Harcos: ");

        lblVarazsloHP.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVarazsloHP.setText("Varázsló: ");

        lblGyoztes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGyoztes.setText("Győztes: ");

        lblMezok.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lblMezok.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMezok.setText("Mezők");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblHarcosHP)
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMezok)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(lblVarazsloHP))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblGyoztes, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lblMezok)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHarcosHP)
                    .addComponent(lblVarazsloHP))
                .addGap(18, 18, 18)
                .addComponent(lblGyoztes)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLepes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUjra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUjraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUjraActionPerformed
        alaphelyzet();
        palyatMutat();
        adatotMutat();
    }//GEN-LAST:event_btnUjraActionPerformed

    private void btnLepesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLepesActionPerformed
        for(int i = 0; i < HOSSZ; i++) mezok[i] = URES;
        int harcosMezo = r.nextInt(HOSSZ), varazsloMezo = r.nextInt(HOSSZ);
        if(harcosMezo == varazsloMezo) {
            mezok[harcosMezo] = HARC;
            harc();
        }
        else {
            mezok[harcosMezo] = HARCOS;
            mezok[varazsloMezo] = VARAZSLO;
        }
        palyatMutat();
        adatotMutat();
    }//GEN-LAST:event_btnLepesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLepes;
    private javax.swing.JButton btnUjra;
    private javax.swing.JLabel lblGyoztes;
    private javax.swing.JLabel lblHarcosHP;
    private javax.swing.JLabel lblMezok;
    private javax.swing.JLabel lblVarazsloHP;
    // End of variables declaration//GEN-END:variables
}
